packages:
<<<<<<< HEAD
  - "apps/*"
  - "packages/*"
=======
    - apps/*
    - packages/*
    - tooling/*

catalog:
    eslint: ^9.36.0
    prettier: ^3.6.2
    tailwindcss: ^4.1.13
    typescript: ^5.6.3
    zod: ^4.1.11
>>>>>>> restart
